export const newspapers=[
    {paper:"Amar Ujala",language:"Hindi"},
    {paper:"Dainik Jagarn",language:"Hindi"},
    {paper:"Rashtriya sahara",language:"Hindi"},
    {paper:"Hindustan",language:"Hindi"},
    {paper:"Times of India",language:"English"},
    {paper:"Hindustan Times",language:"English"},
    {paper:"The Hindu",language:"English"},
    {paper:"The Economics",language:"English"},
    {paper:"Employment News",language:"English"},
    {paper:"Dehradun Clasified",language:"English"},
    {paper:"I- Next",language:"English"},
    {paper:"The Pioneer",language:"English"},
    {paper:"Garhwal Post",language:"English"},
    {paper:"Indian Express",language:"English"},
    {paper:"Business Standard",language:"English"},
]

export const journals = {
    management: [
        { title: "Agrarian South: The Journal Of Political Economy", periodicity: "Tri-Annual" },
        { title: "Asia Pacific Journal Of Management Research And Innovation", periodicity: "Quarterly" },
        { title: "Asian Journal Of Legal Education", periodicity: "Bi-Annual" },
        { title: "Asian Journal Of Management Cases", periodicity: "Bi-Annual" },
        { title: "Environment And Urbanization Asia", periodicity: "Bi-Annual" },
        { title: "Foreign Trade Review", periodicity: "Quarterly" },
        { title: "Global Business Review", periodicity: "Bi-Annual" },
        { title: "Global Journal Of Emerging Market Economies", periodicity: "Bi-Annual" },
        { title: "Iim Kozhikode  Society & Management Review", periodicity: "Bi-Annual" },
        { title: "Indian Journal Of Corporate Governance", periodicity: "Bi-Annual" },
        { title: "International Journal Of Rural Management", periodicity: "Bi-Annual" },
        { title: "Journal Of Creative Communication", periodicity: "Tri-Annual" },
        { title: "Journal Of Emerging Market Finance", periodicity: "Tri-Annual" },
        { title: "Journal Of Enterpreneurship & Innovation In Emerging Economies", periodicity: "Bi-Annual" },
        { title: "Journal Of Entrepreneurship", periodicity: "Bi-Annual" },
        { title: "Journal Of Human Values", periodicity: "Tri-Annual" },
        { title: "Journal Of Infrastructure Development", periodicity: "Bi-Annual" },
        { title: "Journalof Land And Rural Studies", periodicity: "Bi-Annual" },
        { title: "Management And Labour Studies", periodicity: "Quarterly" },
        { title: "Margin - Journal Of Applied Economic Research", periodicity: "Quarterly" },
        { title: "Paradigm", periodicity: "Bi-Annual" },
        { title: "Review Of Market Integration", periodicity: "Tri-Annual" },
        { title: "South Asian Journal Of Business And Management Cases", periodicity: "Tri-Annual" },
        { title: "South Asian Journal Of Human Resource Management", periodicity: "Bi-Annual" },
        { title: "South Asian Journal Of Marcroeconomics And Public Finance", periodicity: "Bi-Annual" },
        { title: "Vikalpa Journal", periodicity: "Quarterly" },
        { title: "Vision", periodicity: "Quarterly" }
    ],
    nursing: [
        { title: "International Journal of Advance Research in Nursing", periodicity: "Biannual" },
        { title: "GFNPSS Global Nursing Journal of India", periodicity: "Triannual" },
        { title: "International Journal of Advance Research in Community Health Nursing", periodicity: "Biannual" },
        { title: "International Journal of Obstetrics and Gynaecological Nursing", periodicity: "Biannual" },
        { title: "International Journal of Pediatrics and Neonatology", periodicity: "Biannual" },
        { title: "International Journal of MidWifery and Nursing Practice", periodicity: "Biannual" },
        { title: "International Journal of Nursing and Health Sciences", periodicity: "Biannual" },
        { title: "International Journal of Nursing Education", periodicity: "Biannual" },
        { title: "FNN Florence Nightingale Journal of Nursing", periodicity: "Triannual" },
        { title: "International Journal of Paediatrics and Geriatrics", periodicity: "Biannual" },
        { title: "International Journal of Advance Research in Medical Surgical Nursing", periodicity: "Biannual" },
        { title: "International Journal of PsyChiatry Research", periodicity: "Biannual" },
        { title: "International Journal of Nursing and Health Research", periodicity: "Biannual" },
        { title: "International Journal of PsyChiatric Nursing", periodicity: "Biannual" },
        { title: "International Journal of Research Paediatric Nursing", periodicity: "Biannual" },
        { title: "International Journal of Advanced Psychiatric Nursing", periodicity: "Biannual" },
        { title: "The Nurse Media Journal of Nursing(NMJN)", periodicity: "Triannual" }
    ],
    pharmacy: [
        { title: "RJPDFT Research Journal of Pharmaceutical Dosage Forms & Technology", periodicity: "Quarterly" },
        { title: "Asian Journal of Pharmaceutical Analysis", periodicity: "Quarterly" },
        { title: "Asian Journal of Pharmaceutical Research", periodicity: "Quarterly" },
        { title: "Asian Journal of Pharmacy and Technology", periodicity: "Quarterly" },
        { title: "Asian Journal of Research in Pharmaceutical Sciences", periodicity: "Quarterly" },
        { title: "Research Journal of Pharmacognosy and Phytochemistry", periodicity: "Quarterly" },
        { title: "RJPPD Research Journal of Pharmacology and Pharmacodynamics", periodicity: "Quarterly" },
        { title: "Research Journal of Pharmacy and Technology", periodicity: "Quarterly" },
        { title: "RJTCS Research Journal of Topical and Cosmetic", periodicity: "Half-Yearly" },
        { title: "International Journal of Drug Regulatory Affairs", periodicity: "Quarterly" }
    ],
    international: [
        { title: "Analytical Chemistry Letters (TACL) ISSN:2229-7928", periodicity: "" },
        { title: "Journal of Biologically Active Products From Nature (TBAP) ISSN:2231-1866", periodicity: "" },
        { title: "Journal of Essential Oil Bearing Plants (TEOP) 0972-060X", periodicity: "" }
    ]
}